
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: veterinaria_container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=amigo123
      - POSTGRES_DB=veterinaria_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_vet:/var/lib/postgresql/data/

volumes:
  postgres_data_vet: